<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;

class UsersTableSeeder extends Seeder
{
    /**
     * Seed 106 users imported from users.csv.
     *
     * Defaults applied:
     *  - password  : '12345678' (bcrypt-hashed)
     *  - status    : active
     *  - is_system_user : true
     *  - employee_id    : derived from the email local-part (upper-cased)
     *
     * Gender values in the source file have been normalised to lowercase
     * ('male' / 'female') to match the users table enum.
     */
    public function run(): void
    {
        $hashedPassword = Hash::make('12345678');
        $now            = Carbon::now();

        $users = [
            [
                'employee_id'    => 'ABHI.GLT',
                'name'           => 'Abinandan Hazarika',
                'email'          => 'abhi.glt@assam.gov.in',
                'mobile'         => '8638869193',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'ANKUR.GLT',
                'name'           => 'Ankur Borah',
                'email'          => 'ankur.glt@assam.gov.in',
                'mobile'         => '7896051473',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'AYUSMAN.GLT',
                'name'           => 'Ayusman Puzari',
                'email'          => 'ayusman.glt@assam.gov.in',
                'mobile'         => '9706771418',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BEDNATH.GLT',
                'name'           => 'Bednath Hazarika',
                'email'          => 'bednath.glt@assam.gov.in',
                'mobile'         => '7002380316',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BIJOY.GLT',
                'name'           => 'Bijoy Gogoi',
                'email'          => 'bijoy.glt@assam.gov.in',
                'mobile'         => '8876862264',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BIMAN.GLT',
                'name'           => 'Biman Pathori',
                'email'          => 'biman.glt@assam.gov.in',
                'mobile'         => '7002576711',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BINU.GLT',
                'name'           => 'Binu Das',
                'email'          => 'binu.glt@assam.gov.in',
                'mobile'         => '6000036470',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BUDHIN.GLT',
                'name'           => 'Budhin Gohain',
                'email'          => 'budhin.glt@assam.gov.in',
                'mobile'         => '9435450726',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'DIPIKA.GLT',
                'name'           => 'Dipika Momin',
                'email'          => 'dipika.glt@assam.gov.in',
                'mobile'         => '7002219064',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'ELANEOG.GLT',
                'name'           => 'Ela Neog',
                'email'          => 'elaneog.glt@assam.gov.in',
                'mobile'         => '9706702156',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'FARID.BARUAH',
                'name'           => 'Farid Hussain Baruah',
                'email'          => 'farid.baruah@assam.gov.in',
                'mobile'         => '9435354170',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'JORSING.GLT',
                'name'           => 'Jorsing Engti',
                'email'          => 'jorsing.glt@assam.gov.in',
                'mobile'         => '8638005213',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'JOYDEEP.GLT',
                'name'           => 'Joydeep Chetia',
                'email'          => 'joydeep.glt@assam.gov.in',
                'mobile'         => '8472995391',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'JULI.GLT',
                'name'           => 'Juli Borah',
                'email'          => 'juli.glt@assam.gov.in',
                'mobile'         => '9101123487',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'KRISHNA.GLT',
                'name'           => 'Krishna Baruah',
                'email'          => 'krishna.glt@assam.gov.in',
                'mobile'         => '8638614717',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'KUNJA.GLT',
                'name'           => 'Kunja Hazarika',
                'email'          => 'kunja.glt@assam.gov.in',
                'mobile'         => '9435867003',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MAMONIH.GLT',
                'name'           => 'Mamoni Hazarika',
                'email'          => 'mamonih.glt@assam.gov.in',
                'mobile'         => '9435660760',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MAMONIS.GLT',
                'name'           => 'Mamoni Saikia',
                'email'          => 'mamonis.glt@assam.gov.in',
                'mobile'         => '9706591324',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MASUM.GLT',
                'name'           => 'Masum Farmin',
                'email'          => 'masum.glt@assam.gov.in',
                'mobile'         => '8638492512',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MOMEE.GLT',
                'name'           => 'Momee Hmar',
                'email'          => 'momee.glt@assam.gov.in',
                'mobile'         => '8638603570',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MONIKHA.GLT',
                'name'           => 'Monikha Saikia',
                'email'          => 'monikha.glt@assam.gov.in',
                'mobile'         => '8402922954',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MUNNA.GLT',
                'name'           => 'Munna Gogoi',
                'email'          => 'munna.glt@assam.gov.in',
                'mobile'         => '9435151228',
                'gender'         => 'male',
                'designation_id' => 11,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'NIJARA.GLT',
                'name'           => 'Nijara Saikia',
                'email'          => 'nijara.glt@assam.gov.in',
                'mobile'         => '7086119589',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RAHUL.GLT',
                'name'           => 'Rahul Gogoi',
                'email'          => 'rahul.glt@assam.gov.in',
                'mobile'         => '7002323368',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'NIREN.GLT',
                'name'           => 'Niren Baruah',
                'email'          => 'niren.glt@assam.gov.in',
                'mobile'         => '9854436132',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PAMELA.GLT',
                'name'           => 'Pamela Hansepi',
                'email'          => 'pamela.glt@assam.gov.in',
                'mobile'         => '9401126513',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PARTHA.GLT',
                'name'           => 'Partha Pratim Saikia',
                'email'          => 'partha.glt@assam.gov.in',
                'mobile'         => '8638643969',
                'gender'         => 'male',
                'designation_id' => 13,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'POLASH.GLT',
                'name'           => 'Polash Loying',
                'email'          => 'polash.glt@assam.gov.in',
                'mobile'         => '7002207320',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PRANJIT.GLT',
                'name'           => 'Pranjiit Saikia',
                'email'          => 'pranjit.glt@assam.gov.in',
                'mobile'         => '7002786332',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PRATAP.GLT',
                'name'           => 'Pratap Ch Saikia',
                'email'          => 'pratap.glt@assam.gov.in',
                'mobile'         => '9678782322',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PRATYUSH.GLT',
                'name'           => 'Pratyush Parasar Sarma',
                'email'          => 'pratyush.glt@assam.gov.in',
                'mobile'         => '7002983643',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RANJIT.GLT',
                'name'           => 'Ranjit Sarma',
                'email'          => 'ranjit.glt@assam.gov.in',
                'mobile'         => '8399055375',
                'gender'         => 'male',
                'designation_id' => 17,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RANTUMONI.GLT',
                'name'           => 'Rantumoni Das',
                'email'          => 'rantumoni.glt@assam.gov.in',
                'mobile'         => '9401105378',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'ROSHMI.GLT',
                'name'           => 'Rashmi Rekha Bora',
                'email'          => 'roshmi.glt@assam.gov.in',
                'mobile'         => '7399199027',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RINTIMONI.GLT',
                'name'           => 'Rintimoni Dutta',
                'email'          => 'rintimoni.glt@assam.gov.in',
                'mobile'         => '8472983867',
                'gender'         => 'female',
                'designation_id' => 20,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RIPUN.GLT',
                'name'           => 'RIPUN DUTTA',
                'email'          => 'ripun.glt@assam.gov.in',
                'mobile'         => '9435234628',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SAMPRITY.GLT',
                'name'           => 'Samprity Kaushik',
                'email'          => 'samprity.glt@assam.gov.in',
                'mobile'         => '7002440207',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SANJUKTA.GLT',
                'name'           => 'Sanjukta Gogoi',
                'email'          => 'sanjukta.glt@assam.gov.in',
                'mobile'         => '7002432017',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SIKHAMONI.GLT',
                'name'           => 'Sikha Moni Chutia',
                'email'          => 'sikhamoni.glt@assam.gov.in',
                'mobile'         => '7638071333',
                'gender'         => 'female',
                'designation_id' => 18,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MUSANNA.GLT',
                'name'           => 'Syed Musanna Rahman',
                'email'          => 'musanna.glt@assam.gov.in',
                'mobile'         => '8638500327',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'TRIDIP.GLT',
                'name'           => 'Tridip Saikia',
                'email'          => 'tridip.glt@assam.gov.in',
                'mobile'         => '9435488128',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'UJJAL.GLT',
                'name'           => 'Ujjal Dutta',
                'email'          => 'ujjal.glt@assam.gov.in',
                'mobile'         => '9864704411',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'UJJWAL.GLT',
                'name'           => 'UJJWAL BORA',
                'email'          => 'ujjwal.glt@assam.gov.in',
                'mobile'         => '7002406225',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'AMLAN.PHUKAN',
                'name'           => 'Amlan Phukan, ACS',
                'email'          => 'amlan.phukan@assam.gov.in',
                'mobile'         => '8011639282',
                'gender'         => 'male',
                'designation_id' => 4,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BITUL.GLT',
                'name'           => 'Bitul Hazarika',
                'email'          => 'bitul.glt@assam.gov.in',
                'mobile'         => '9101168273',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MUSFIQUR.GLT',
                'name'           => 'Musfiqur Rahman',
                'email'          => 'musfiqur.glt@assam.gov.in',
                'mobile'         => '9101157116',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'TARUNI.GLT',
                'name'           => 'Taruni Rajkhowa',
                'email'          => 'taruni.glt@assam.gov.in',
                'mobile'         => '9365728909',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BINOD.GLT',
                'name'           => 'Binod Hazarika',
                'email'          => 'binod.glt@assam.gov.in',
                'mobile'         => '7896606098',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MONOJ.GLT',
                'name'           => 'Manoj Kumar Saikia',
                'email'          => 'monoj.glt@assam.gov.in',
                'mobile'         => '9101712154',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MUNIN.GLT',
                'name'           => 'Munindra Tanti',
                'email'          => 'munin.glt@assam.gov.in',
                'mobile'         => '8638611703',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'TULTUL.GLT',
                'name'           => 'Tultul Das',
                'email'          => 'tultul.glt@assam.gov.in',
                'mobile'         => '7002274754',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SWAGATA.GLT',
                'name'           => 'Swagata Sarma',
                'email'          => 'swagata.glt@assam.gov.in',
                'mobile'         => '8723014004',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'KULDIP.HAZARIKA',
                'name'           => 'Kuldip Hazarika, ACS',
                'email'          => 'kuldip.hazarika@assam.gov.in',
                'mobile'         => '9854180171',
                'gender'         => 'male',
                'designation_id' => 3,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SAKHTARA.AHMED',
                'name'           => 'Sultana Akhtara Ahmed, ACS',
                'email'          => 'sakhtara.ahmed@assam.gov.in',
                'mobile'         => '9954302968',
                'gender'         => 'female',
                'designation_id' => 3,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RITURAJ.BORGOHAIN',
                'name'           => 'Rituraj Borgohain',
                'email'          => 'rituraj.borgohain@assam.gov.in',
                'mobile'         => '7002274743',
                'gender'         => 'male',
                'designation_id' => 9,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PABITRA.GLT',
                'name'           => 'Pabitra Kr Sarmah',
                'email'          => 'pabitra.glt@assam.gov.in',
                'mobile'         => '9365080617',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'POLASH.HAZARIKA',
                'name'           => 'Polash Hazarika',
                'email'          => 'polash.hazarika@gmail.com',
                'mobile'         => '9101589922',
                'gender'         => 'male',
                'designation_id' => 25,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'JITU.GLT',
                'name'           => 'Jitu Gogoi',
                'email'          => 'jitu.glt@assam.gov.in',
                'mobile'         => '9401126344',
                'gender'         => 'male',
                'designation_id' => 21,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SRI.ANIL.GHOSH',
                'name'           => 'Anil Ghosh',
                'email'          => 'sri.anil.ghosh@gmail.com',
                'mobile'         => '7002328446',
                'gender'         => 'male',
                'designation_id' => 26,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'Y.KASHYAP',
                'name'           => 'Yasubant Kashyap',
                'email'          => 'y.kashyap@gmail.com',
                'mobile'         => '8471902265',
                'gender'         => 'male',
                'designation_id' => 28,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'ABHILASH.GLT',
                'name'           => 'Abhilash Sharma',
                'email'          => 'abhilash.glt@assam.gov.in',
                'mobile'         => '7002775172',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'HIRONGOGOI.GLT',
                'name'           => 'Hiron Gogoi',
                'email'          => 'hirongogoi.glt@assam.gov.in',
                'mobile'         => '8638862350',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'GOLAGHAT',
                'name'           => 'NIC, Golaghat',
                'email'          => 'golaghat@nic.in',
                'mobile'         => '9864260148',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'VIVEK.GLT',
                'name'           => 'Vivek Gogoi',
                'email'          => 'vivek.glt@assam.gov.in',
                'mobile'         => '7002612947',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MAUSUM.GLT',
                'name'           => 'Mausum Raj Khound',
                'email'          => 'mausum.glt@assam.gov.in',
                'mobile'         => '9101080837',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MIRMILI.GLT',
                'name'           => 'Mirmili Hansepi',
                'email'          => 'mirmili.glt@assam.gov.in',
                'mobile'         => '9678758250',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'AMIRUL.GLT',
                'name'           => 'Amirul Hussain',
                'email'          => 'amirul.glt@assam.gov.in',
                'mobile'         => '7002451408',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'DEHADUTTA70',
                'name'           => 'Himanshu Dutta',
                'email'          => 'dehadutta70@gmail.com',
                'mobile'         => '8638707257',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'JITEN.GLT',
                'name'           => 'Jiten Gogoi',
                'email'          => 'jiten.glt@assam.gov.in',
                'mobile'         => '7002299388',
                'gender'         => 'male',
                'designation_id' => 12,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SUBHAMHALDER293',
                'name'           => 'Subham Halder',
                'email'          => 'subhamhalder293@gmail.com',
                'mobile'         => '9954275609',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SUMANBORAHBOKAKHAT',
                'name'           => 'Suman Borah',
                'email'          => 'Sumanborahbokakhat@gmail.com',
                'mobile'         => '8638239207',
                'gender'         => 'male',
                'designation_id' => 27,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'FARUKAZIZ53',
                'name'           => 'Faruk Aziz',
                'email'          => 'farukaziz53@gmail.com',
                'mobile'         => '8876454128',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'CHANDASURAJ809',
                'name'           => 'Suraj Chanda',
                'email'          => 'chandasuraj809@gmail.com',
                'mobile'         => '7896321838',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SMITIREKHAB',
                'name'           => 'Smritirekha Bora',
                'email'          => 'smitirekhab@gmail.com',
                'mobile'         => '7002209177',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MOYUR.DHAN',
                'name'           => 'Moyur Jyoti Saikia',
                'email'          => 'moyur.dhan@assam.gov.in',
                'mobile'         => '9954608754',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'KHOGEN.GLT',
                'name'           => 'Khogen Chutia',
                'email'          => 'khogen.glt@assam.gov.in',
                'mobile'         => '94013182262',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'ABHILASHDAS.2023',
                'name'           => 'Abhilash Das, ACS',
                'email'          => 'abhilashdas.2023@assam.gov.in',
                'mobile'         => '9706539443',
                'gender'         => 'male',
                'designation_id' => 4,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MOUSUMIBARMAN.2023',
                'name'           => 'Mousumi Barman, ACS',
                'email'          => 'mousumibarman.2023@assam.gov.in',
                'mobile'         => '7002032375',
                'gender'         => 'female',
                'designation_id' => 4,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'NEHAPHUKON.2023',
                'name'           => 'Neha Phukon, ACS',
                'email'          => 'nehaphukon.2023@assam.gov.in',
                'mobile'         => '8638122394',
                'gender'         => 'female',
                'designation_id' => 4,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RATULROY.2023',
                'name'           => 'Ratul Roy, ACS',
                'email'          => 'ratulroy.2023@assam.gov.in',
                'mobile'         => '8369692764',
                'gender'         => 'male',
                'designation_id' => 4,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MANUJKR.BORA',
                'name'           => 'Manuj Kr. Bora',
                'email'          => 'manujkr.bora@assam.gov.in',
                'mobile'         => '7002328297',
                'gender'         => 'male',
                'designation_id' => 31,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'HOMENCHUTIA1',
                'name'           => 'Homen Chutia',
                'email'          => 'homenchutia1@gmail.com',
                'mobile'         => '8721848925',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BORUAHPRYAS',
                'name'           => 'Prayas Borauh',
                'email'          => 'boruahpryas@gmail.com',
                'mobile'         => '9401911280',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RUBY.RAY',
                'name'           => 'Ruby Kumari Ray, ACS',
                'email'          => 'ruby.ray@assam.gov.in',
                'mobile'         => '8486636550',
                'gender'         => 'female',
                'designation_id' => 5,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'DEBAJITGOGOI198902',
                'name'           => 'Debojit Gogoi',
                'email'          => 'debajitgogoi198902@gmail.com',
                'mobile'         => '9101831432',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'GSINGH.ACS',
                'name'           => 'Mr. Gurnel singh, ACS',
                'email'          => 'gsingh.acs@assam.gov.in',
                'mobile'         => '9435159160',
                'gender'         => 'female',
                'designation_id' => 2,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SUPRIYA.BAWLARI',
                'name'           => 'Supriya Bawlari, ACS',
                'email'          => 'Supriya.bawlari@assam.gov.in',
                'mobile'         => '8486228948',
                'gender'         => 'female',
                'designation_id' => 4,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'DC-GOLAGHAT',
                'name'           => 'Smt. Pubali Gohain, ACS',
                'email'          => 'dc-golaghat@nic.in',
                'mobile'         => '9864024779',
                'gender'         => 'female',
                'designation_id' => 1,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SEUJ.DOHUTIA',
                'name'           => 'Dr. Seuj Dohutia, ACS',
                'email'          => 'Seuj.dohutia@assam.gov.in',
                'mobile'         => '7002479199',
                'gender'         => 'male',
                'designation_id' => 4,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'ASHUTOSH.DEKA',
                'name'           => 'Ashutosh Deka, ACS',
                'email'          => 'ashutosh.deka@assam.gov.in',
                'mobile'         => '9854984921',
                'gender'         => 'male',
                'designation_id' => 3,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MONIKA.BORAH',
                'name'           => 'Monika Borah, ACS',
                'email'          => 'monika.borah@assam.gov.in',
                'mobile'         => '8876992296',
                'gender'         => 'female',
                'designation_id' => 3,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'JOYA.MECH26',
                'name'           => 'Joya Mech',
                'email'          => 'joya.mech26@assam.gov.in',
                'mobile'         => '8486782549',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'REEMAREKHAB',
                'name'           => 'Reema Rekha Borpatra Bora',
                'email'          => 'reemarekhab@gmail.com',
                'mobile'         => '8638050330',
                'gender'         => 'female',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PRATIKSHA.GLT',
                'name'           => 'Pratiksha Goswami',
                'email'          => 'pratiksha.glt@assam.gov.in',
                'mobile'         => '9954380089',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'ANSUMAN.BORAH26',
                'name'           => 'Ansuman Bora',
                'email'          => 'ansuman.borah26@assam.gov.in',
                'mobile'         => '9954566314',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'ALAKESH.KAKATI2013',
                'name'           => 'Alakesh Kakati',
                'email'          => 'alakesh.kakati2013@assam.gov.in',
                'mobile'         => '6001703212',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MANAB.NATHR69',
                'name'           => 'Manab Nath',
                'email'          => 'manab.nathr69@gmail.com',
                'mobile'         => '8638334018',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'SPODCGLT',
                'name'           => 'Pankaj Khangia',
                'email'          => 'spodcglt@gmail.com',
                'mobile'         => '9365177918',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'KOUSTABHBORUAH',
                'name'           => 'Koustabh Boruah',
                'email'          => 'koustabhboruah@gmail.com',
                'mobile'         => '7002062174',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'BIPULKUMERDEKA40',
                'name'           => 'Bipul Kumar Deka',
                'email'          => 'bipulkumerdeka40@gmail.com',
                'mobile'         => '9435062296',
                'gender'         => 'male',
                'designation_id' => 30,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'GOLAP.GLT',
                'name'           => 'Golap Boruah',
                'email'          => 'Golap.glt@assam.gov.in',
                'mobile'         => '9435576084',
                'gender'         => 'male',
                'designation_id' => 16,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PRASTUTI.BORA',
                'name'           => 'Prastuti Bora',
                'email'          => 'prastuti.bora@assam.gov.in',
                'mobile'         => '8134974680',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'MRIDUSMITA.BORA26',
                'name'           => 'Mridusmita Bora',
                'email'          => 'mridusmita.bora26@assam.gov.in',
                'mobile'         => '8011616099',
                'gender'         => 'female',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'RANJANPROTIM.GLT',
                'name'           => 'Ranjan Protim Neog',
                'email'          => 'ranjanprotim.glt@assam.gov.in',
                'mobile'         => '8638691705',
                'gender'         => 'male',
                'designation_id' => 19,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'PULAKGOGOI85',
                'name'           => 'Pulak Gogoi',
                'email'          => 'pulakgogoi85@gmail.com',
                'mobile'         => '8876249937',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'NF2.GG.AS',
                'name'           => 'Pankaj Medhi',
                'email'          => 'nf2.gg.as@support.gov.in',
                'mobile'         => '7002490210',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'employee_id'    => 'NFO1.GG.AS',
                'name'           => 'Atikur Rahman',
                'email'          => 'nfo1.gg.as@support.gov.in',
                'mobile'         => '7002322020',
                'gender'         => 'male',
                'designation_id' => 22,
                'role_id'        => 5,
                'password'       => $hashedPassword,
                'is_system_user' => true,
                'status'         => 'active',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];

        // Insert in chunks to avoid hitting DB placeholder limits
        foreach (array_chunk($users, 50) as $chunk) {
            DB::table('users')->insert($chunk);
        }

        $this->command->info('UsersTableSeeder: ' . count($users) . ' users seeded successfully.');
    }
}